// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACR_CazDNZPKSNz83EVoGrbnPku9YLckU',
    appId: '1:758316269099:web:e1ba378d4615ee4c89346e',
    messagingSenderId: '758316269099',
    projectId: 'formlytai',
    authDomain: 'formlytai.firebaseapp.com',
    storageBucket: 'formlytai.firebasestorage.app',
    measurementId: 'G-VM913TWN6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKMGd1S9SfT5E5xY7TyzKeJ-z8hyka2pE',
    appId: '1:758316269099:android:20f0521a5c18da0f89346e',
    messagingSenderId: '758316269099',
    projectId: 'formlytai',
    storageBucket: 'formlytai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyDy46xA5H-j9QNIFIlqGXInbidNENgc8',
    appId: '1:758316269099:ios:120a7d44b5a9515b89346e',
    messagingSenderId: '758316269099',
    projectId: 'formlytai',
    storageBucket: 'formlytai.firebasestorage.app',
    iosBundleId: 'com.example.farmlytAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyDy46xA5H-j9QNIFIlqGXInbidNENgc8',
    appId: '1:758316269099:ios:120a7d44b5a9515b89346e',
    messagingSenderId: '758316269099',
    projectId: 'formlytai',
    storageBucket: 'formlytai.firebasestorage.app',
    iosBundleId: 'com.example.farmlytAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACR_CazDNZPKSNz83EVoGrbnPku9YLckU',
    appId: '1:758316269099:web:5ffe281b6363c6be89346e',
    messagingSenderId: '758316269099',
    projectId: 'formlytai',
    authDomain: 'formlytai.firebaseapp.com',
    storageBucket: 'formlytai.firebasestorage.app',
    measurementId: 'G-9HQ10MX1XN',
  );
}
